<a href="https://colab.research.google.com/github/heyavie/CSST101-3A-AY2627/blob/main/CSST101LABACT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Creating Variables**

In [3]:
attendance_rate <- 0.82
average_grade <- 0.78

cat("Attendance:", attendance_rate * 100, "%\n")
cat("Average Grade:", average_grade * 100, "%\n\n")

Attendance: 82 %
Average Grade: 78 %

2. **Basic Calculations**

In [8]:
quiz <- 85
laboratory <- 90
project <- 88
exam <- 80

weight_quiz <- 0.20
weight_lab <- 0.25
weight_project <- 0.25
weight_exam <- 0.30

final_grade <- (
    (quiz * weight_quiz)
    + (laboratory * weight_lab)
    + (project * weight_project)
    + (exam * weight_exam)
)

cat("Weighted Final Grade:", final_grade, "\n")

Weighted Final Grade: 85.5

**3. Using Comparison Operators**

In [4]:
attendance <- 82
average <- 78

print(attendance < 75)
print(average < 75)
print(attendance >= 75)

[1] FALSE
[1] FALSE
[1] TRUE

4. **Using AND and OR**

In [11]:
attendance <- 70
grade <- 82

at_risk_both <- (attendance < 75) && (grade < 75)
cat("At risk (Both < 75):", at_risk_both, "\n")

at_risk_either <- (attendance < 75) || (grade < 75)
cat("At risk (Either < 75):", at_risk_either, "\n\n")

At risk (Both < 75): FALSE
At risk (Either < 75): TRUE

**5. Simple IF Statement**

In [12]:
if (grade >= 75)(
  print("PASS")
)

[1] "PASS"

[1] "PASS"

**6. Multiple Conditions**

In [13]:
if (grade >= 90)(
  print("Excellent")
) else if (grade >= 85)(
  print("Very Good")
) else if (grade >= 80)(
  print("Good")
) else if (grade >= 75)(
  print("Passed")
) else if (grade < 75)(
  print("Failed")
)

[1] "Good"

[1] "Good"

**7. Creating a Function**

In [14]:
classify_grade <- function(score) {
  if (score >= 90) {
    return("Excellent")
  } else if (score >= 85) {
    return("Very Good")
  } else if (score >= 80) {
    return("Good")
  } else if (score >= 75) {
    return("Passed")
  } else {
    return("Failed")
  }
}

**8. Creating a Data Frame**

In [15]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65)
)

print(students)

  Student_ID Attendance Grade
1       S001         95    90
2       S002         72    70
3       S003         88    85
4       S004         79    77
5       S005         68    65

**9. Adding a Classification Column**

In [16]:
students$Performance <- ifelse(
  students$Grade >= 80,
  "Good",
  ifelse(
    students$Grade >= 75,
    "Passed",
    "Failed"
  )
)

students

  Student_ID Attendance Grade Performance
1 S001       95         90    Good
2 S002       72         70    Failed
3 S003       88         85    Good
4 S004       79         77    Passed
5 S005       68         65    Failed

**10. Creating a Simple Rule-Based System**

In [20]:
check_risk <- function(attendance, grade) {
  if (attendance < 75 & grade < 75) {
    return("High Risk")
  } else {
    return("Low Risk")
  }
}

**11. Apply the Rule to Multiple Students**

In [30]:
student_risk <- function(attendance, grade) {
  if (attendance < 75 & grade < 75) {
    return("High Risk")
  }
  else if (attendance < 85 || grade < 80) {
    return("Moderate Risk")
  }
  else {
    return("Low Risk")
  }
}

students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65)
)


students$Risk <- mapply(
  student_risk,
  students$Attendance,
  students$Grade
)

students

  Student_ID Attendance Grade Risk
1 S001       95         90    Low Risk
2 S002       72         70    High Risk
3 S003       88         85    Low Risk
4 S004       79         77    Moderate Risk
5 S005       68         65    High Risk

**12. Count the Results**

1. There are 2 students classified as High Risk.
2. There is 1 students classified as Moderate Risk.
3. There are 2 students classified as Low Risk.
4. The High Risk and Low Risk groups are tied for having the largest number of students, with 2 students each.

**13. Create a Visualization**

1. The graph shows the distribution and total count of students across each risk category.
2. Base on the data set, High Risk and Low Risk are tied for having the most students, with 2 in each category.
3. The university should implement targeted academic interventions and support programs for students in the High and Moderate Risk categories to help improve their attendance and grades.

**14. Add a Recommendation**

In [29]:
get_recommendation <- function(risk_level) {
  if (risk_level == "High Risk") {
    return("Immediate academic intervention")
  } else if (risk_level == "Moderate Risk") {
    return("Academic monitoring")
  } else {
    return("Continue regular monitoring")

  }
}

students$Recommendation <- sapply(students$Risk, get_recommendation)

students

  Student_ID Attendance Grade Risk      Recommendation
1 S001       95         90    Low Risk  Continue regular monitoring
2 S002       72         70    High Risk Immediate academic intervention
3 S003       88         85    Low Risk  Continue regular monitoring
4 S004       79         77    Low Risk  Continue regular monitoring
5 S005       68         65    High Risk Immediate academic intervention

**15. Final System**

In [32]:
evaluate_student <- function(student_id, attendance, grade) {
  if (attendance < 75 || grade < 75) {
    risk_level <- "High Risk"
    recommendation <- "Immediate academic intervention"
  } else if (attendance < 85 || grade < 85) {
    risk_level <- "Moderate Risk"
    recommendation <- "Monitor progress and offer support"
  } else {
    risk_level <- "Low Risk"
    recommendation <- "On track"
  }

  cat("Student ID:", student_id, "\n")
  cat("Attendance:", paste0(attendance, "%"), "\n")
  cat("Grade:", grade, "\n\n")
  cat("Risk Level:", risk_level, "\n\n")
  cat("Recommendation:\n")
  cat(recommendation, "\n")
}

evaluate_student(student_id = "S002", attendance = 72, grade = 70)

Student ID: S002
Attendance: 72%
Grade: 70

Risk Level: High Risk

Recommendation:
Immediate academic intervention